FROM ghcr.io/nersc/interactem/operator

WORKDIR /app
COPY ./pyproject.toml ./poetry.lock ./README.md /app/

RUN poetry install --no-root --without test

COPY ./distiller_streaming/ /app/distiller_streaming/
RUN poetry install --without test