FROM ghcr.io/nersc/interactem/operator

WORKDIR /app
COPY ./distiller-pipeline/pyproject.toml ./distiller-pipeline/poetry.lock ./distiller-pipeline/README.md /app/

RUN poetry install --no-root

COPY ./distiller-pipeline/distiller_pipeline/ /app/distiller_pipeline/
RUN poetry install

COPY ./distiller-counted-data-reader/run.py /app/run.py