services:
  db:
    restart: "no"

  backend:
    restart: "no"
    ports:
      - "8888:8888"
    volumes:
      - ./backend/app/:/interactem/app
      - ./backend/core/:/interactem/core
      - ./backend/sfapi_models/:/interactem/sfapi_models
    command: 
      - fastapi
      - run
      - --reload
      - "interactem/app/main.py"
    environment:
      SMTP_HOST: "mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"

  orchestrator:
    restart: "no"
    volumes:
      - ./backend/app/:/interactem/app
      - ./backend/core/:/interactem/core
      - ./backend/sfapi_models/:/interactem/sfapi_models

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  # frontend:
  #   restart: "no"
  #   build:
  #     context: ./frontend
  #     args:
  #       - VITE_API_URL=http://${DOMAIN?Variable not set}
  #       - NODE_ENV=development
