services:
  db:
    restart: "no"
    ports:
      - "5432:5432"

  backend:
    restart: "no"
    ports:
      - "8888:8888"
    volumes:
      - ./backend/app/:/app
      - ./backend/core/:/core
    build:
      context: ./backend/
      dockerfile: ./app/Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: /start-reload.sh
    environment:
      SMTP_HOST: "mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"

  orchestrator:
    restart: "no"
    volumes:
      - ./backend/orchestrator/:/app
      - ./backend/core/:/core
    build:
      context: ./backend/
      dockerfile: ./orchestrator/Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}


  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  # frontend:
  #   restart: "no"
  #   build:
  #     context: ./frontend
  #     args:
  #       - VITE_API_URL=http://${DOMAIN?Variable not set}
  #       - NODE_ENV=development
