services:
  db:
    restart: "no"

  backend:
    restart: "no"
    ports:
      - "8888:8888"
    volumes:
      - ./backend/app/:/interactem/app
      - ./backend/core/:/interactem/core
      - ./backend/sfapi_models/:/interactem/sfapi_models
      - ./operators/:/operators
    command: 
      - fastapi
      - run
      - --reload
      - "interactem/app/main.py"

  orchestrator:
    volumes:
      - ./backend/orchestrator/:/interactem/orchestrator
      - ./backend/core/:/interactem/core
      - ./backend/sfapi_models/:/interactem/sfapi_models