services:
  db:
    restart: "no"

  backend:
    restart: "no"
    ports:
      - "8888:8888"
    volumes:
      - ./backend/app/:/interactem/app
      - ./backend/core/:/interactem/core
      - ./backend/sfapi_models/:/interactem/sfapi_models
    command: 
      - fastapi
      - run
      - --reload
      - "interactem/app/main.py"

  orchestrator:
    restart: "no"
    volumes:
      - ./backend/orchestrator/:/interactem/orchestrator
      - ./backend/core/:/interactem/core
      - ./backend/sfapi_models/:/interactem/sfapi_models


  # frontend:
  #   restart: "no"
  #   build:
  #     context: ./frontend
  #     args:
  #       - VITE_API_URL=http://${DOMAIN?Variable not set}
  #       - NODE_ENV=development
