FROM python:3.12-slim-bookworm

WORKDIR /app/

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives/* 

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./operators/pyproject.toml ./operators/poetry.lock* /app/

COPY ./core/ /core/

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --only main ; fi"

COPY ./operators/operators /app/operators/

COPY ./operators/containerfiles/error/run.py /app/run.py

ENV PYTHONUNBUFFERED=1

ENTRYPOINT [ "/usr/local/bin/python",  "/app/run.py"]