"""add pipeline deployments table

Revision ID: 4fd674e69396
Revises: ae4ed8e4c67b
Create Date: 2025-07-16 01:22:32.152627

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4fd674e69396'
down_revision = 'ae4ed8e4c67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelinedeployment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'FAILED_TO_START', 'RUNNING', 'CANCELLED', name='pipelinedeploymentstate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), # edited to include server_default
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), # edited to include server_default
    sa.ForeignKeyConstraint(['pipeline_id', 'revision_id'], ['pipelinerevision.pipeline_id', 'pipelinerevision.revision_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelinedeployment_pipeline_id'), 'pipelinedeployment', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipelinedeployment_revision_id'), 'pipelinedeployment', ['revision_id'], unique=False)
    op.create_index(op.f('ix_pipelinedeployment_state'), 'pipelinedeployment', ['state'], unique=False)
    op.drop_column('pipeline', 'running')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('running', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_pipelinedeployment_state'), table_name='pipelinedeployment')
    op.drop_index(op.f('ix_pipelinedeployment_revision_id'), table_name='pipelinedeployment')
    op.drop_index(op.f('ix_pipelinedeployment_pipeline_id'), table_name='pipelinedeployment')
    op.drop_table('pipelinedeployment')
    # ### end Alembic commands ###
