"""add pipeline name

Revision ID: 60a2bc7c4aea
Revises: 8254e462f00f
Create Date: 2025-04-19 13:04:23.374238

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '60a2bc7c4aea'
down_revision = '8254e462f00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.create_index(op.f('ix_pipeline_name'), 'pipeline', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_name'), table_name='pipeline')
    op.drop_column('pipeline', 'name')
    # ### end Alembic commands ###
