"""add deployment states

Revision ID: 628f190fb478
Revises: b76f7b29a6e7
Create Date: 2025-11-05 05:04:01.040520

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '628f190fb478'
down_revision = 'b76f7b29a6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='pipelinedeploymentstate',
        new_values=['PENDING', 'AGENTS_ASSIGNED', 'FAILED_TO_START', 'FAILURE_ON_AGENT', 'RUNNING', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='pipelinedeployment', column_name='state')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='pipelinedeploymentstate',
        new_values=['PENDING', 'FAILED_TO_START', 'RUNNING', 'CANCELLED'],
        affected_columns=[TableReference(table_schema='public', table_name='pipelinedeployment', column_name='state')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
