"""add pipeline revisions

Revision ID: 8254e462f00f
Revises: d1149e7679f9
Create Date: 2025-04-18 16:21:57.158290

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8254e462f00f'
down_revision = 'd1149e7679f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelinerevision',
    sa.Column('pipeline_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('tag', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pipeline_id', 'revision_id')
    )
    op.create_index(op.f('ix_pipelinerevision_pipeline_id'), 'pipelinerevision', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipelinerevision_revision_id'), 'pipelinerevision', ['revision_id'], unique=False)
    op.add_column('pipeline', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('pipeline', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_pipeline_created_at'), 'pipeline', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_updated_at'), 'pipeline', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_updated_at'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_created_at'), table_name='pipeline')
    op.drop_column('pipeline', 'created_at')
    op.drop_column('pipeline', 'updated_at')
    op.drop_index(op.f('ix_pipelinerevision_revision_id'), table_name='pipelinerevision')
    op.drop_index(op.f('ix_pipelinerevision_pipeline_id'), table_name='pipelinerevision')
    op.drop_table('pipelinerevision')
    # ### end Alembic commands ###
