"""current_revision_id

Revision ID: ae4ed8e4c67b
Revises: 60a2bc7c4aea
Create Date: 2025-04-19 18:06:17.099537

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ae4ed8e4c67b'
down_revision = '60a2bc7c4aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('current_revision_id', sa.Integer(), nullable=True))

    # Update existing NULL values to 0
    op.execute('UPDATE pipeline SET current_revision_id = 0 WHERE current_revision_id IS NULL')

    # Alter the column to be non-nullable
    op.alter_column('pipeline', 'current_revision_id',
               existing_type=sa.Integer(),
               nullable=False)

    op.create_index(op.f('ix_pipeline_current_revision_id'), 'pipeline', ['current_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_current_revision_id'), table_name='pipeline')
    op.drop_column('pipeline', 'current_revision_id')
    # ### end Alembic commands ###
