"""add_operator_positions_to_pipeline_revision

Revision ID: b76f7b29a6e7
Revises: d259ec167e13
Create Date: 2025-10-22 03:10:20.279675

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b76f7b29a6e7'
down_revision = 'd259ec167e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelinerevision', sa.Column('positions', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelinerevision', 'positions')
    # ### end Alembic commands ###
