FROM interactem/interactem

# --- Install interactem operators deps ---
WORKDIR /interactem/operators
RUN touch README.md
COPY ./operators/pyproject.toml ./operators/poetry.lock* ./

# --- Install interactem operators ---
COPY ./operators/operators/ ./operators/
RUN poetry install --only main

ENTRYPOINT [ "python", "/app/run.py" ]