FROM interactem/interactem:latest

# --- Install interactem operators deps ---
WORKDIR /interactem/operators
RUN touch README.md
COPY ./operators/pyproject.toml ./operators/poetry.lock* ./
RUN poetry install --no-root

# --- Install interactem operators ---
COPY ./operators/operators/ ./operators/
RUN poetry install --only main

COPY ./operators/startup.py /app/startup.py

ENTRYPOINT [ "python", "/app/startup.py" ]