FROM interactem-base

WORKDIR /interactem/app
COPY ./app/pyproject.toml ./app/poetry.lock* ./
RUN touch README.md
COPY ./sfapi_models/ /interactem/sfapi_models/
RUN poetry install --no-root --without dev

ENV PYTHONPATH=/interactem/app

ENV MODULE_NAME=interactem.app.main

COPY ./app/scripts ./scripts

COPY ./app/alembic.ini ./

COPY ./app/prestart.sh ./

COPY ./app/tests-start.sh ./

COPY ./app/interactem ./interactem

RUN poetry install --only-root

CMD ["fastapi", "run", "--workers", "4", "interactem/app/main.py"]