FROM ghcr.io/nersc/interactem/interactem:latest

# --- Install interactem operators deps ---
WORKDIR /interactem/operators
RUN touch README.md
COPY ./operators/pyproject.toml ./operators/poetry.lock* ./
RUN poetry install --no-root

# --- Install interactem operators ---
COPY ./operators/interactem/ ./interactem
RUN poetry install --only main

COPY ./operators/startup.py /app/startup.py

ENV PYTHONPATH=/interactem/operators

ENTRYPOINT [ "python", "/app/startup.py" ]