FROM samwelborn/stempy:py310-43b9b6e

WORKDIR /app/

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives/* 

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

RUN pip install scipy

# Copy poetry.lock* in case it doesn't exist in the repo
WORKDIR /interactem/operators
COPY ./backend/operators/pyproject.toml ./operators/poetry.lock* ./
COPY ./backend/core/ /interactem/core/
RUN poetry install --no-root

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --only main ; fi"

ENV PYTHONUNBUFFERED=1

COPY ./backend/operators/operators /interactem/operators/operators
RUN touch /interactem/operators/README.md
RUN poetry install --only main

COPY ./operators/electron-count/run.py /app/run.py

ENTRYPOINT [ "python", "/app/startup.py" ]