FROM ghcr.io/nersc/interactem/operator AS operator-base

# Main build using stempy as the base
FROM samwelborn/stempy:py310-f685f4d

WORKDIR /app/

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/apt/archives/* 

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

# Copy the interactem operator files from the base image
COPY --from=operator-base /interactem/operators /interactem/operators
COPY --from=operator-base /interactem/core /interactem/core

# Install additional dependencies needed for this specific operator
RUN pip install scipy

# Copy the electron-count specific run script
COPY ./run.py /app/run.py

# Set Python path
ENV PYTHONPATH=/interactem/operators
ENV PYTHONUNBUFFERED=1

# Copy the startup script
COPY --from=operator-base /app/startup.py /app/startup.py

ENTRYPOINT ["python", "/app/startup.py"]