FROM ghcr.io/nersc/interactem/operator AS operator-base

# Main build using stempy as the base
FROM docker.io/samwelborn/stempy:py310-f685f4d

WORKDIR /app/

# Copy the interactem operator files from the base image
COPY --from=operator-base /interactem/operators /interactem/operators
COPY --from=operator-base /interactem/core /interactem/core

RUN cd /interactem/operators/ && pip install . scipy

# Copy the electron-count specific run script
COPY ./run.py /app/run.py

# Set Python path
ENV PYTHONUNBUFFERED=1

# Copy the startup script
COPY --from=operator-base /app/startup.py /app/startup.py

ENTRYPOINT ["python", "/app/startup.py"]