FROM ghcr.io/nersc/interactem/operator

WORKDIR /app
COPY ./distiller-streaming/pyproject.toml ./distiller-streaming/poetry.lock ./distiller-streaming/README.md /app/

RUN poetry install --no-root

COPY ./distiller-streaming/distiller_streaming/ /app/distiller_streaming/
RUN poetry install

COPY ./virtual-bfdf/run.py /app/run.py