STREAM_PIPELINES = "pipelines"
SUBJECT_PIPELINES_NEW = f"{STREAM_PIPELINES}.new"
SUBJECT_PIPELINES_RUN = f"{STREAM_PIPELINES}.run"
SUBJECT_PIPELINES_STATUS = f"{STREAM_PIPELINES}.status"
SUBJECT_PIPELINES_STOP = f"{STREAM_PIPELINES}.stop"

STREAM_AGENTS = "agents"

BUCKET_AGENTS = "agents"
BUCKET_AGENTS_TTL = 30

STREAM_SFAPI = "sfapi"
SUBJECT_SFAPI_JOBS_SUBMIT = f"{STREAM_SFAPI}.jobs.submit"

SFAPI_SERVICE_NAME = "sfapi-service"
SFAPI_GROUP_NAME = f"{STREAM_SFAPI}-micro"
SFAPI_STATUS_ENDPOINT = "status"

STREAM_NOTIFICATIONS = "notifications"
SUBJECT_NOTIFICATIONS_INFO = f"{STREAM_NOTIFICATIONS}.info"
SUBJECT_NOTIFICATIONS_ERRORS = f"{STREAM_NOTIFICATIONS}.errors"

STREAM_OPERATORS = "operators"

BUCKET_OPERATORS = "operators"
BUCKET_OPERATORS_TTL = 30

OPERATOR_ID_ENV_VAR = "INTERACTEM_AGENT_ID"
OPERATOR_CLASS_NAME = "Operator"
OPERATOR_RUN_LOCATION = "/app/run.py"

STREAM_METRICS = "metrics"

BUCKET_METRICS = "metrics"
BUCKET_METRICS_TTL = 30

BUCKET_PIPELINES = "pipelines"
BUCKET_PIPELINES_TTL = 30

STREAM_PARAMETERS = "parameters"
STREAM_PARAMETERS_UPDATE = f"{STREAM_PARAMETERS}.update"

STREAM_IMAGES = "images"

STREAM_TABLES = "tables"

MOUNT_DIR = "/mnt"

PACKAGE_DIR_IN_CONTAINER = "/interactem"
