STREAM_PIPELINES = "pipelines"
SUBJECT_PIPELINES_NEW = f"{STREAM_PIPELINES}.new"
SUBJECT_PIPELINES_RUN = f"{STREAM_PIPELINES}.run"
SUBJECT_PIPELINES_STATUS = f"{STREAM_PIPELINES}.status"

STREAM_AGENTS = "agents"

BUCKET_AGENTS = "agents"
BUCKET_AGENTS_TTL = 30

SFAPI_SERVICE_NAME = "sfapi-service"
SFAPI_GROUP_NAME = "sfapi"
SFAPI_SUBMIT_ENDPOINT = "submit"
SFAPI_STATUS_ENDPOINT = "status"

STREAM_OPERATORS = "operators"

BUCKET_OPERATORS = "operators"
BUCKET_OPERATORS_TTL = 30

OPERATOR_ID_ENV_VAR = "INTERACTEM_AGENT_ID"
OPERATOR_CLASS_NAME = "Operator"
OPERATOR_RUN_LOCATION = "/app/run.py"

STREAM_METRICS = "metrics"

BUCKET_METRICS = "metrics"
BUCKET_METRICS_TTL = 30

BUCKET_PIPELINES = "pipelines"
BUCKET_PIPELINES_TTL = 30

STREAM_PARAMETERS = "parameters"
STREAM_PARAMETERS_UPDATE = f"{STREAM_PARAMETERS}.update"

STREAM_IMAGES = "images"

MOUNT_DIR = "/mnt"

PACKAGE_DIR_IN_CONTAINER = "/interactem"
