FROM distiller-streaming

# had to add cffi because ncempy messes with that package when adding, and nkeys acts up...
RUN poetry add ncempy cffi

COPY ./run.py /app/run.py

RUN mkdir -p /output
RUN mkdir -p /vacuum_scan