config:
  cluster:
    enabled: true

  jetstream:
    enabled: true

  # Uncomment for external access through a websocket (outside NERSC)
  websocket:
    enabled: true
    port: 8080
    ingress:
      enabled: true
      hosts:
        # - <your domain cname>
        - ingress.interactem.production.svc.spin.nersc.org
      path: /
      pathType: Exact
      className: nginx
      tlsSecretName: tls-cert
      name: ingress
      merge:
        metadata:
          annotations:
            nginx.ingress.kubernetes.io/whitelist-source-range: >-
              128.55.206.0/24, 128.55.205.0/24, 128.55.64.0/18
            # this is to allow the ACME challenge to pass through the ingress given
            # the above whitelist. TODO: Not sure if it works.
            nginx.ingress.kubernetes.io/server-snippet: |
                location /.well-known/acme-challenge/ {
                    allow all;
                }

natsBox:
  container:
    image:
      tag: 0.14.4-nonroot


extraResources:
  - apiVersion: v1
    kind: Service
    metadata:
      name: nats-external
      namespace: interactem
      labels:
        app.kubernetes.io/component: nats
        app.kubernetes.io/instance: nats
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: nats
    spec:
      type: LoadBalancer
      selector:
        app.kubernetes.io/component: nats
        app.kubernetes.io/instance: nats
        app.kubernetes.io/name: nats
      ports:
        - name: nats
          port: 5672 # exposed port
          targetPort: 4222 # internal port
