STREAM_PIPELINES = "pipelines"
SUBJECT_PIPELINES_NEW = f"{STREAM_PIPELINES}.new"
SUBJECT_PIPELINES_RUN = f"{STREAM_PIPELINES}.run"
SUBJECT_PIPELINES_STATUS = f"{STREAM_PIPELINES}.status"

STREAM_AGENTS = "agents"

BUCKET_AGENTS = "agents"
BUCKET_AGENTS_TTL = 30

STREAM_OPERATORS = "operators"

BUCKET_OPERATORS = "operators"
BUCKET_OPERATORS_TTL = 30
