STREAM_PIPELINES = "pipelines"
SUBJECT_PIPELINES_NEW = f"{STREAM_PIPELINES}.new"
SUBJECT_PIPELINES_RUN = f"{STREAM_PIPELINES}.run"
SUBJECT_PIPELINES_STATUS = f"{STREAM_PIPELINES}.status"

STREAM_AGENTS = "agents"

BUCKET_AGENTS = "agents"
BUCKET_AGENTS_TTL = 30

DEFAULT_COMPOSE_NATS_ADDRESS: str = "nats://nats1:4222"
DEFAULT_NATS_ADDRESS: str = "nats://localhost:4222"
