// Generated using claude from the constants in the backend
/**
 * These constants are used throughout interactEM, mostly for NATS streams and buckets.
 * At top level are what we want to talk about (the streams), like status, metrics, and notifications.
 * We then define who we are talking about, like pipelines, agents, operators, and ports.
 * Underneath this level is typically the ID of the subject, like a pipeline ID, agent ID, operator ID, or port ID.
 *
 * Later, we could sneak a user ID between the type and the ID, but we don't do that yet.
 *
 * We should ideally keep these short, nats recommends <16 tokens (hierarchy levels) and <256 characters total.
 * ref: https://github.com/nats-io/nats.docs/blob/master/nats-concepts/subjects.md
 */

const NATS_TIMEOUT_DEFAULT = 10

// Streams/buckets
const BUCKET_STATUS = "stat"
const BUCKET_STATUS_TTL = 30

const STREAM_METRICS = "met"
const SUBJECT_METRICS_ALL = `${STREAM_METRICS}.>`
const BUCKET_METRICS = STREAM_METRICS
const BUCKET_METRICS_TTL = 30

const STREAM_NOTIFICATIONS = "noti"
const SUBJECT_NOTIFICATIONS_ALL = `${STREAM_NOTIFICATIONS}.>`

const STREAM_PARAMETERS = "par"
const SUBJECT_PARAMETERS_ALL = `${STREAM_PARAMETERS}.>`

const STREAM_DEPLOYMENTS = "depl"
const SUBJECT_DEPLOYMENTS_ALL = `${STREAM_DEPLOYMENTS}.>`

const STREAM_IMAGES = "img"
const SUBJECT_IMAGES_ALL = `${STREAM_IMAGES}.>`

const STREAM_TABLES = "tbl"
const SUBJECT_TABLES_ALL = `${STREAM_TABLES}.>`

const STREAM_LOGS = "log"
const SUBJECT_LOGS_ALL = `${STREAM_LOGS}.>`

const STREAM_SFAPI = "sfapi"
const SUBJECT_SFAPI_JOBS = `${STREAM_SFAPI}.jobs`
const SUBJECT_SFAPI_ALL = `${STREAM_SFAPI}.>`

// Common
const PIPELINES = "pipe"
const OPERATORS = "op"
const AGENTS = "agent"
const PORTS = "port"
const ERRORS = "err"
const INFO = "info"
const UPDATES = "upd"
const TRIGGERS = "trig"

// Pipelines
const SUBJECT_PIPELINES_METRICS = `${STREAM_METRICS}.${PIPELINES}`
const SUBJECT_PIPELINES_DEPLOYMENTS = `${STREAM_DEPLOYMENTS}.${PIPELINES}`
const SUBJECT_PIPELINES_DEPLOYMENTS_NEW = `${SUBJECT_PIPELINES_DEPLOYMENTS}.new`
const SUBJECT_PIPELINES_DEPLOYMENTS_UPDATE = `${SUBJECT_PIPELINES_DEPLOYMENTS}.${UPDATES}`
const SUBJECT_PIPELINES_DEPLOYMENTS_STOP = `${SUBJECT_PIPELINES_DEPLOYMENTS}.stop`

// Agents
// TODO: come back to agent errors/info when doing logging
const SUBJECT_AGENTS_NOTIFICATIONS = `${STREAM_NOTIFICATIONS}.${AGENTS}`
const SUBJECT_AGENTS_NOTIFICATIONS_ERRORS = `${SUBJECT_AGENTS_NOTIFICATIONS}.${ERRORS}`
const SUBJECT_AGENTS_NOTIFICATIONS_INFO = `${SUBJECT_AGENTS_NOTIFICATIONS}.${INFO}`
const SUBJECT_AGENTS_DEPLOYMENTS = `${STREAM_DEPLOYMENTS}.${AGENTS}`
const SUBJECT_AGENTS_LOGS = `${STREAM_LOGS}.${AGENTS}`

// Operators
const SUBJECT_OPERATORS_PARAMETERS = `${STREAM_PARAMETERS}.${OPERATORS}`
// we get operator parameters updates from the frontend, we use a different subject
// for the update channel
const SUBJECT_OPERATORS_PARAMETERS_UPDATE = `${SUBJECT_OPERATORS_PARAMETERS}.${UPDATES}`
// TODO: come back to operator errors/info when doing logging
const SUBJECT_OPERATORS_NOTIFICATIONS_ERRORS = `${STREAM_NOTIFICATIONS}.${OPERATORS}.${ERRORS}`
const SUBJECT_OPERATORS_NOTIFICATIONS_INFO = `${STREAM_NOTIFICATIONS}.${OPERATORS}.${INFO}`
const SUBJECT_OPERATORS_METRICS = `${STREAM_METRICS}.${OPERATORS}`
const SUBJECT_OPERATORS_DEPLOYMENTS = `${STREAM_DEPLOYMENTS}.${OPERATORS}`
const SUBJECT_OPERATORS_TRIGGERS = `${TRIGGERS}.${OPERATORS}`

// Logs - hierarchical structure:
const SUBJECT_LOGS_DEPLOYMENTS = `${STREAM_LOGS}.depl`

// Notifications
const SUBJECT_NOTIFICATIONS_ERRORS = `${STREAM_NOTIFICATIONS}.${ERRORS}`
const SUBJECT_NOTIFICATIONS_INFO = `${STREAM_NOTIFICATIONS}.${INFO}`

// Vector
const SUBJECT_LOGS_VECTOR = `${STREAM_LOGS}.vector`

export {
  NATS_TIMEOUT_DEFAULT,
  BUCKET_STATUS,
  BUCKET_STATUS_TTL,
  STREAM_METRICS,
  SUBJECT_METRICS_ALL,
  BUCKET_METRICS,
  BUCKET_METRICS_TTL,
  STREAM_NOTIFICATIONS,
  SUBJECT_NOTIFICATIONS_ALL,
  STREAM_PARAMETERS,
  SUBJECT_PARAMETERS_ALL,
  STREAM_DEPLOYMENTS,
  SUBJECT_DEPLOYMENTS_ALL,
  STREAM_IMAGES,
  SUBJECT_IMAGES_ALL,
  STREAM_TABLES,
  SUBJECT_TABLES_ALL,
  STREAM_LOGS,
  SUBJECT_LOGS_ALL,
  STREAM_SFAPI,
  SUBJECT_SFAPI_JOBS,
  SUBJECT_SFAPI_ALL,
  PIPELINES,
  OPERATORS,
  AGENTS,
  PORTS,
  ERRORS,
  INFO,
  UPDATES,
  TRIGGERS,
  SUBJECT_PIPELINES_METRICS,
  SUBJECT_PIPELINES_DEPLOYMENTS,
  SUBJECT_PIPELINES_DEPLOYMENTS_NEW,
  SUBJECT_PIPELINES_DEPLOYMENTS_UPDATE,
  SUBJECT_PIPELINES_DEPLOYMENTS_STOP,
  SUBJECT_AGENTS_NOTIFICATIONS,
  SUBJECT_AGENTS_NOTIFICATIONS_ERRORS,
  SUBJECT_AGENTS_NOTIFICATIONS_INFO,
  SUBJECT_AGENTS_DEPLOYMENTS,
  SUBJECT_AGENTS_LOGS,
  SUBJECT_OPERATORS_PARAMETERS,
  SUBJECT_OPERATORS_PARAMETERS_UPDATE,
  SUBJECT_OPERATORS_NOTIFICATIONS_ERRORS,
  SUBJECT_OPERATORS_NOTIFICATIONS_INFO,
  SUBJECT_OPERATORS_METRICS,
  SUBJECT_OPERATORS_DEPLOYMENTS,
  SUBJECT_OPERATORS_TRIGGERS,
  SUBJECT_LOGS_DEPLOYMENTS,
  SUBJECT_NOTIFICATIONS_ERRORS,
  SUBJECT_NOTIFICATIONS_INFO,
  SUBJECT_LOGS_VECTOR,
}
